# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanat', '0002_auto_20171016_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
    ]
