# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanat', '0004_auto_20171016_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field=60, upload_to='', width_field=60),
        ),
    ]
